version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: ssa-postgres
    ports:
      - "5555:5432"
    environment:
      POSTGRES_USER: ssa
      POSTGRES_PASSWORD: ssa
      POSTGRES_DB: ssa
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 